### ISSUE TITLE
Appstream metadata is unavailable

### ISSUE THREAD

**Issue by ghost** [flathub/org.freedesktop.LinuxAudio.Plugins.TAP#1]
It isn't possible to uninstall `org.freedesktop.LinuxAudio.*` plugins using GNOME Software/KDE Discover because the appstream metadata doesn't seem to be present.

## Additional info
- Version 1.0.1
- Branch 21.08
- Fedora 37 Workstation

**Comment by hfiguiere** [comment]
this is a gnome software problem then.

**Comment by ghost** [comment]
> this is a gnome software problem then.

I couldn't find appstream metadata for `org.freedesktop.LinuxAudio.*` in `/usr/share/metainfo` or in `/usr/share/appdata`. Doesn't seem to be a GNOME Software issue.

**Comment by ghost** [comment]
@hfiguiere ping

https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1847#note_1524456
